<?xml version="1.0" standalone="yes" ?>
<!DOCTYPE document [
        <!ELEMENT document (employee)*>
        <!ELEMENT employee (name+, hiredate?, projects*)>
        <!ELEMENT name (lastname, firstname)>
        <!ELEMENT lastname (#PCDATA)>
        <!ELEMENT firstname (#PCDATA)>
        <!ELEMENT hiredate (#PCDATA)>
        <!ELEMENT projects (product, id, price)>
        <!ELEMENT product (#PCDATA)>
        <!ELEMENT id (#PCDATA)>
        <!ELEMENT price (#PCDATA)>
        ]>
<document>
    <employee>
        <name>
            <lastname>Kelly</lastname>
            <firstname>Grace</firstname>
        </name>
        <hiredate>October 15, 2005</hiredate>
        <projects>
            <product>Printer</product>
            <id>111</id>
            <price>$111.00</price>
        </projects>
        <projects>
            <product>Laptop</product>
            <id>222</id>
            <price>$989.00</price>
        </projects>
    </employee>
</document>